import { Project, Staff, Assignment } from './types';

export const mockProjects: Project[] = [
  {
    id: 'proj-001',
    name: 'E-Commerce Platform Redesign',
    client: 'TechRetail Inc.',
    description: 'Complete redesign and modernization of the existing e-commerce platform with improved UX and performance.',
    status: 'active',
    startDate: '2024-01-15',
    endDate: '2024-06-30',
    budget: 450000,
    spent: 285000,
    revenue: 450000,
    teamSize: 8,
    techStack: ['React', 'Node.js', 'PostgreSQL', 'AWS'],
    priority: 'high',
    progress: 65,
    projectManager: 'Sarah Johnson',
    staffAssigned: ['staff-001', 'staff-002', 'staff-003', 'staff-004']
  },
  {
    id: 'proj-002',
    name: 'Mobile Banking App',
    client: 'FinanceFirst Bank',
    description: 'Native mobile application for iOS and Android with secure banking features.',
    status: 'active',
    startDate: '2024-02-01',
    endDate: '2024-08-15',
    budget: 680000,
    spent: 340000,
    revenue: 680000,
    teamSize: 10,
    techStack: ['React Native', 'TypeScript', 'Firebase', 'Node.js'],
    priority: 'critical',
    progress: 45,
    projectManager: 'Michael Chen',
    staffAssigned: ['staff-005', 'staff-006', 'staff-007', 'staff-008', 'staff-009']
  },
  {
    id: 'proj-003',
    name: 'AI-Powered Analytics Dashboard',
    client: 'DataInsights Corp',
    description: 'Machine learning powered analytics platform for business intelligence.',
    status: 'planning',
    startDate: '2024-04-01',
    endDate: '2024-10-31',
    budget: 520000,
    spent: 45000,
    revenue: 520000,
    teamSize: 6,
    techStack: ['Python', 'TensorFlow', 'React', 'MongoDB'],
    priority: 'medium',
    progress: 15,
    projectManager: 'Emily Davis',
    staffAssigned: ['staff-010', 'staff-011']
  },
  {
    id: 'proj-004',
    name: 'Healthcare Management System',
    client: 'MediCare Solutions',
    description: 'Comprehensive healthcare management platform for hospitals and clinics.',
    status: 'active',
    startDate: '2023-11-01',
    endDate: '2024-05-30',
    budget: 890000,
    spent: 712000,
    revenue: 890000,
    teamSize: 12,
    techStack: ['Angular', '.NET Core', 'SQL Server', 'Azure'],
    priority: 'high',
    progress: 80,
    projectManager: 'Robert Martinez',
    staffAssigned: ['staff-012', 'staff-013', 'staff-014', 'staff-015']
  },
  {
    id: 'proj-005',
    name: 'IoT Fleet Management',
    client: 'LogisticsPro',
    description: 'Real-time fleet tracking and management system using IoT devices.',
    status: 'on-hold',
    startDate: '2024-03-15',
    endDate: '2024-09-30',
    budget: 320000,
    spent: 120000,
    revenue: 320000,
    teamSize: 5,
    techStack: ['Vue.js', 'Python', 'InfluxDB', 'Docker'],
    priority: 'low',
    progress: 35,
    projectManager: 'Lisa Anderson',
    staffAssigned: ['staff-016', 'staff-017']
  }
];

export const mockStaff: Staff[] = [
  {
    id: 'staff-001',
    name: 'John Smith',
    email: 'john.smith@company.com',
    role: 'Senior Full Stack Developer',
    department: 'Engineering',
    status: 'fully-booked',
    availability: 0,
    billableHours: 168,
    totalHours: 168,
    skills: [
      { name: 'React', level: 'expert', yearsOfExperience: 5 },
      { name: 'Node.js', level: 'senior', yearsOfExperience: 4 },
      { name: 'AWS', level: 'mid', yearsOfExperience: 2 }
    ],
    languages: ['English', 'Spanish'],
    programmingLanguages: ['JavaScript', 'TypeScript', 'Python'],
    experience: 8,
    rate: 150,
    currentProjects: ['proj-001'],
    location: 'New York, USA',
    timezone: 'EST'
  },
  {
    id: 'staff-002',
    name: 'Emma Wilson',
    email: 'emma.wilson@company.com',
    role: 'UX/UI Designer',
    department: 'Design',
    status: 'partially-booked',
    availability: 40,
    billableHours: 120,
    totalHours: 168,
    skills: [
      { name: 'Figma', level: 'expert', yearsOfExperience: 4 },
      { name: 'Adobe XD', level: 'senior', yearsOfExperience: 3 },
      { name: 'User Research', level: 'senior', yearsOfExperience: 5 }
    ],
    languages: ['English', 'French'],
    programmingLanguages: ['HTML', 'CSS', 'JavaScript'],
    experience: 6,
    rate: 120,
    currentProjects: ['proj-001', 'proj-002'],
    location: 'London, UK',
    timezone: 'GMT'
  },
  {
    id: 'staff-003',
    name: 'David Lee',
    email: 'david.lee@company.com',
    role: 'Backend Developer',
    department: 'Engineering',
    status: 'available',
    availability: 100,
    billableHours: 0,
    totalHours: 168,
    skills: [
      { name: 'Python', level: 'expert', yearsOfExperience: 6 },
      { name: 'Django', level: 'senior', yearsOfExperience: 4 },
      { name: 'PostgreSQL', level: 'senior', yearsOfExperience: 5 }
    ],
    languages: ['English', 'Mandarin'],
    programmingLanguages: ['Python', 'Go', 'SQL'],
    experience: 7,
    rate: 140,
    currentProjects: [],
    location: 'San Francisco, USA',
    timezone: 'PST'
  },
  {
    id: 'staff-004',
    name: 'Maria Garcia',
    email: 'maria.garcia@company.com',
    role: 'DevOps Engineer',
    department: 'Infrastructure',
    status: 'partially-booked',
    availability: 60,
    billableHours: 80,
    totalHours: 168,
    skills: [
      { name: 'Kubernetes', level: 'senior', yearsOfExperience: 3 },
      { name: 'Docker', level: 'expert', yearsOfExperience: 5 },
      { name: 'CI/CD', level: 'senior', yearsOfExperience: 4 }
    ],
    languages: ['English', 'Spanish', 'Portuguese'],
    programmingLanguages: ['Python', 'Bash', 'YAML'],
    experience: 5,
    rate: 135,
    currentProjects: ['proj-001', 'proj-004'],
    location: 'Madrid, Spain',
    timezone: 'CET'
  },
  {
    id: 'staff-005',
    name: 'Alex Chen',
    email: 'alex.chen@company.com',
    role: 'Mobile Developer',
    department: 'Engineering',
    status: 'fully-booked',
    availability: 0,
    billableHours: 168,
    totalHours: 168,
    skills: [
      { name: 'React Native', level: 'expert', yearsOfExperience: 4 },
      { name: 'iOS Development', level: 'senior', yearsOfExperience: 3 },
      { name: 'Android Development', level: 'senior', yearsOfExperience: 3 }
    ],
    languages: ['English', 'Mandarin', 'Japanese'],
    programmingLanguages: ['Swift', 'Kotlin', 'JavaScript'],
    experience: 6,
    rate: 145,
    currentProjects: ['proj-002'],
    location: 'Toronto, Canada',
    timezone: 'EST'
  },
  {
    id: 'staff-006',
    name: 'Sophie Martin',
    email: 'sophie.martin@company.com',
    role: 'QA Engineer',
    department: 'Quality Assurance',
    status: 'partially-booked',
    availability: 50,
    billableHours: 84,
    totalHours: 168,
    skills: [
      { name: 'Selenium', level: 'senior', yearsOfExperience: 4 },
      { name: 'Jest', level: 'mid', yearsOfExperience: 2 },
      { name: 'API Testing', level: 'senior', yearsOfExperience: 5 }
    ],
    languages: ['English', 'French', 'German'],
    programmingLanguages: ['JavaScript', 'Python', 'Java'],
    experience: 5,
    rate: 110,
    currentProjects: ['proj-002', 'proj-004'],
    location: 'Paris, France',
    timezone: 'CET'
  },
  {
    id: 'staff-007',
    name: 'James Brown',
    email: 'james.brown@company.com',
    role: 'Data Scientist',
    department: 'Data & Analytics',
    status: 'available',
    availability: 100,
    billableHours: 0,
    totalHours: 168,
    skills: [
      { name: 'Machine Learning', level: 'expert', yearsOfExperience: 5 },
      { name: 'TensorFlow', level: 'senior', yearsOfExperience: 3 },
      { name: 'Data Analysis', level: 'expert', yearsOfExperience: 6 }
    ],
    languages: ['English'],
    programmingLanguages: ['Python', 'R', 'SQL'],
    experience: 7,
    rate: 160,
    currentProjects: [],
    location: 'Austin, USA',
    timezone: 'CST'
  },
  {
    id: 'staff-008',
    name: 'Olivia Taylor',
    email: 'olivia.taylor@company.com',
    role: 'Product Manager',
    department: 'Product',
    status: 'partially-booked',
    availability: 30,
    billableHours: 100,
    totalHours: 168,
    skills: [
      { name: 'Product Strategy', level: 'expert', yearsOfExperience: 7 },
      { name: 'Agile', level: 'expert', yearsOfExperience: 6 },
      { name: 'User Research', level: 'senior', yearsOfExperience: 5 }
    ],
    languages: ['English', 'Italian'],
    programmingLanguages: ['SQL'],
    experience: 9,
    rate: 180,
    currentProjects: ['proj-002', 'proj-001'],
    location: 'Milan, Italy',
    timezone: 'CET'
  },
  {
    id: 'staff-009',
    name: 'Kevin Johnson',
    email: 'kevin.johnson@company.com',
    role: 'Frontend Developer',
    department: 'Engineering',
    status: 'on-leave',
    availability: 0,
    billableHours: 0,
    totalHours: 0,
    skills: [
      { name: 'Vue.js', level: 'senior', yearsOfExperience: 3 },
      { name: 'React', level: 'mid', yearsOfExperience: 2 },
      { name: 'CSS', level: 'expert', yearsOfExperience: 5 }
    ],
    languages: ['English'],
    programmingLanguages: ['JavaScript', 'TypeScript', 'HTML'],
    experience: 4,
    rate: 125,
    currentProjects: [],
    location: 'Seattle, USA',
    timezone: 'PST'
  },
  {
    id: 'staff-010',
    name: 'Anna Kowalski',
    email: 'anna.kowalski@company.com',
    role: 'Cloud Architect',
    department: 'Infrastructure',
    status: 'available',
    availability: 100,
    billableHours: 0,
    totalHours: 168,
    skills: [
      { name: 'AWS', level: 'expert', yearsOfExperience: 6 },
      { name: 'Azure', level: 'senior', yearsOfExperience: 4 },
      { name: 'Terraform', level: 'senior', yearsOfExperience: 3 }
    ],
    languages: ['English', 'Polish', 'German'],
    programmingLanguages: ['Python', 'Go', 'HCL'],
    experience: 8,
    rate: 170,
    currentProjects: [],
    location: 'Warsaw, Poland',
    timezone: 'CET'
  }
];

export const mockAssignments: Assignment[] = [
  {
    id: 'assign-001',
    projectId: 'proj-001',
    staffId: 'staff-001',
    role: 'Lead Developer',
    allocation: 100,
    startDate: '2024-01-15',
    endDate: '2024-06-30',
    billableHours: 168
  },
  {
    id: 'assign-002',
    projectId: 'proj-001',
    staffId: 'staff-002',
    role: 'UX Designer',
    allocation: 60,
    startDate: '2024-01-15',
    endDate: '2024-06-30',
    billableHours: 100
  },
  {
    id: 'assign-003',
    projectId: 'proj-002',
    staffId: 'staff-005',
    role: 'Mobile Developer',
    allocation: 100,
    startDate: '2024-02-01',
    endDate: '2024-08-15',
    billableHours: 168
  },
  {
    id: 'assign-004',
    projectId: 'proj-002',
    staffId: 'staff-002',
    role: 'UI Designer',
    allocation: 40,
    startDate: '2024-02-01',
    endDate: '2024-08-15',
    billableHours: 20
  }
];