import { Project, Staff, Assignment } from './types';

export const mockProjects: Project[] = [
  {
    id: 'proj-001',
    name: 'E-Commerce Platform Redesign',
    client: 'Siemens AG',
    description: 'Complete redesign and modernization of the existing e-commerce platform with improved UX and performance.',
    status: 'active',
    startDate: '2024-01-15',
    endDate: '2024-06-30',
    budget: 450000,
    spent: 285000,
    revenue: 450000,
    receivedAmount: 320000,
    teamSize: 8,
    techStack: ['React', 'Node.js', 'PostgreSQL', 'AWS'],
    priority: 'high',
    progress: 65,
    projectManager: 'Maria Popescu',
    teamLead: 'staff-001',
    staffAssigned: ['staff-001', 'staff-002', 'staff-003', 'staff-004']
  },
  {
    id: 'proj-002',
    name: 'Mobile Banking App',
    client: 'Deutsche Bank',
    description: 'Native mobile application for iOS and Android with secure banking features.',
    status: 'active',
    startDate: '2024-02-01',
    endDate: '2024-08-15',
    budget: 680000,
    spent: 340000,
    revenue: 680000,
    receivedAmount: 408000,
    teamSize: 10,
    techStack: ['React Native', 'TypeScript', 'Firebase', 'Node.js'],
    priority: 'critical',
    progress: 45,
    projectManager: 'Alexandru Ionescu',
    teamLead: 'staff-005',
    staffAssigned: ['staff-005', 'staff-006', 'staff-007', 'staff-008', 'staff-009']
  },
  {
    id: 'proj-003',
    name: 'AI-Powered Analytics Dashboard',
    client: 'SAP SE',
    description: 'Machine learning powered analytics platform for business intelligence.',
    status: 'planning',
    startDate: '2024-04-01',
    endDate: '2024-10-31',
    budget: 520000,
    spent: 45000,
    revenue: 520000,
    receivedAmount: 104000,
    teamSize: 6,
    techStack: ['Python', 'TensorFlow', 'React', 'MongoDB'],
    priority: 'medium',
    progress: 15,
    projectManager: 'Elena Stoica',
    teamLead: 'staff-010',
    staffAssigned: ['staff-010', 'staff-011']
  },
  {
    id: 'proj-004',
    name: 'Healthcare Management System',
    client: 'Bayer AG',
    description: 'Comprehensive healthcare management platform for hospitals and clinics.',
    status: 'active',
    startDate: '2023-11-01',
    endDate: '2024-05-30',
    budget: 890000,
    spent: 712000,
    revenue: 890000,
    receivedAmount: 623000,
    teamSize: 12,
    techStack: ['Angular', '.NET Core', 'SQL Server', 'Azure'],
    priority: 'high',
    progress: 80,
    projectManager: 'Andrei Marin',
    teamLead: 'staff-012',
    staffAssigned: ['staff-012', 'staff-013', 'staff-014', 'staff-015']
  },
  {
    id: 'proj-005',
    name: 'IoT Fleet Management',
    client: 'Mercedes-Benz Group',
    description: 'Real-time fleet tracking and management system using IoT devices.',
    status: 'on-hold',
    startDate: '2024-03-15',
    endDate: '2024-09-30',
    budget: 320000,
    spent: 120000,
    revenue: 320000,
    receivedAmount: 96000,
    teamSize: 5,
    techStack: ['Vue.js', 'Python', 'InfluxDB', 'Docker'],
    priority: 'low',
    progress: 35,
    projectManager: 'Diana Constantinescu',
    teamLead: 'staff-016',
    staffAssigned: ['staff-016', 'staff-017']
  }
];

export const mockStaff: Staff[] = [
  {
    id: 'staff-001',
    name: 'Ion Popescu',
    email: 'ion.popescu@company.com',
    role: 'Senior Full Stack Developer',
    department: 'Engineering',
    status: 'fully-booked',
    availability: 0,
    billableHours: 168,
    totalHours: 168,
    billableUtilization: 85,
    skills: [
      { name: 'React', level: 'expert', yearsOfExperience: 5 },
      { name: 'Node.js', level: 'senior', yearsOfExperience: 4 },
      { name: 'AWS', level: 'mid', yearsOfExperience: 2 }
    ],
    languages: ['Romanian', 'English', 'German'],
    programmingLanguages: ['JavaScript', 'TypeScript', 'Python'],
    experience: 8,
    internalRate: 75,
    clientRate: 150,
    currentProjects: ['proj-001'],
    location: 'Bucharest, Romania',
    timezone: 'EET',
    phone: '+1 (555) 123-4567',
    startDate: '2022-03-15',
    employmentType: 'full-time'
  },
  {
    id: 'staff-002',
    name: 'Maria Ionescu',
    email: 'maria.ionescu@company.com',
    role: 'UX/UI Designer',
    department: 'Design',
    status: 'partially-booked',
    availability: 40,
    billableHours: 120,
    totalHours: 168,
    billableUtilization: 78,
    skills: [
      { name: 'Figma', level: 'expert', yearsOfExperience: 4 },
      { name: 'Adobe XD', level: 'senior', yearsOfExperience: 3 },
      { name: 'User Research', level: 'senior', yearsOfExperience: 5 }
    ],
    languages: ['Romanian', 'English', 'French'],
    programmingLanguages: ['HTML', 'CSS', 'JavaScript'],
    experience: 6,
    internalRate: 60,
    clientRate: 120,
    currentProjects: ['proj-001', 'proj-002'],
    location: 'Cluj-Napoca, Romania',
    timezone: 'EET',
    phone: '+44 20 7946 0958',
    startDate: '2021-09-01',
    employmentType: 'full-time'
  },
  {
    id: 'staff-003',
    name: 'Andrei Stan',
    email: 'andrei.stan@company.com',
    role: 'Backend Developer',
    department: 'Engineering',
    status: 'available',
    availability: 100,
    billableHours: 0,
    totalHours: 168,
    billableUtilization: 0,
    skills: [
      { name: 'Python', level: 'expert', yearsOfExperience: 6 },
      { name: 'Django', level: 'senior', yearsOfExperience: 4 },
      { name: 'PostgreSQL', level: 'senior', yearsOfExperience: 5 }
    ],
    languages: ['Romanian', 'English', 'German'],
    programmingLanguages: ['Python', 'Go', 'SQL'],
    experience: 7,
    internalRate: 70,
    clientRate: 140,
    currentProjects: [],
    location: 'Timișoara, Romania',
    timezone: 'EET',
    phone: '+1 (555) 234-5678',
    startDate: '2021-11-15',
    employmentType: 'full-time'
  },
  {
    id: 'staff-004',
    name: 'Elena Marin',
    email: 'elena.marin@company.com',
    role: 'DevOps Engineer',
    department: 'Infrastructure',
    status: 'partially-booked',
    availability: 60,
    billableHours: 80,
    totalHours: 168,
    billableUtilization: 65,
    skills: [
      { name: 'Kubernetes', level: 'senior', yearsOfExperience: 3 },
      { name: 'Docker', level: 'expert', yearsOfExperience: 5 },
      { name: 'CI/CD', level: 'senior', yearsOfExperience: 4 }
    ],
    languages: ['Romanian', 'English', 'German'],
    programmingLanguages: ['Python', 'Bash', 'YAML'],
    experience: 5,
    internalRate: 85,
    clientRate: 135,
    currentProjects: ['proj-001', 'proj-004'],
    location: 'Iași, Romania',
    timezone: 'EET',
    phone: '+34 91 123 4567',
    startDate: '2022-06-01',
    employmentType: 'full-time'
  },
  {
    id: 'staff-005',
    name: 'Alexandru Dobre',
    email: 'alexandru.dobre@company.com',
    role: 'Mobile Developer',
    department: 'Engineering',
    status: 'fully-booked',
    availability: 0,
    billableHours: 168,
    totalHours: 168,
    billableUtilization: 90,
    skills: [
      { name: 'React Native', level: 'expert', yearsOfExperience: 4 },
      { name: 'iOS Development', level: 'senior', yearsOfExperience: 3 },
      { name: 'Android Development', level: 'senior', yearsOfExperience: 3 }
    ],
    languages: ['Romanian', 'English', 'German'],
    programmingLanguages: ['Swift', 'Kotlin', 'JavaScript'],
    experience: 6,
    internalRate: 95,
    clientRate: 145,
    currentProjects: ['proj-002'],
    location: 'Constanța, Romania',
    timezone: 'EET',
    phone: '+1 (416) 123-4567',
    startDate: '2021-08-01',
    employmentType: 'full-time'
  },
  {
    id: 'staff-006',
    name: 'Ana Stoica',
    email: 'ana.stoica@company.com',
    role: 'QA Engineer',
    department: 'Quality Assurance',
    status: 'partially-booked',
    availability: 50,
    billableHours: 84,
    totalHours: 168,
    billableUtilization: 70,
    skills: [
      { name: 'Selenium', level: 'senior', yearsOfExperience: 4 },
      { name: 'Jest', level: 'mid', yearsOfExperience: 2 },
      { name: 'API Testing', level: 'senior', yearsOfExperience: 5 }
    ],
    languages: ['Romanian', 'German', 'English'],
    programmingLanguages: ['JavaScript', 'Python', 'Java'],
    experience: 5,
    internalRate: 65,
    clientRate: 110,
    currentProjects: ['proj-002', 'proj-004'],
    location: 'Brașov, Romania',
    timezone: 'EET',
    phone: '+33 1 23 45 67 89',
    startDate: '2021-10-15',
    employmentType: 'full-time'
  },
  {
    id: 'staff-007',
    name: 'Mihai Vasile',
    email: 'mihai.vasile@company.com',
    role: 'Data Scientist',
    department: 'Data & Analytics',
    status: 'available',
    availability: 100,
    billableHours: 0,
    totalHours: 168,
    billableUtilization: 0,
    skills: [
      { name: 'Machine Learning', level: 'expert', yearsOfExperience: 5 },
      { name: 'TensorFlow', level: 'senior', yearsOfExperience: 3 },
      { name: 'Data Analysis', level: 'expert', yearsOfExperience: 6 }
    ],
    languages: ['Romanian', 'English'],
    programmingLanguages: ['Python', 'R', 'SQL'],
    experience: 7,
    internalRate: 90,
    clientRate: 160,
    currentProjects: [],
    location: 'Sibiu, Romania',
    timezone: 'EET',
    phone: '+1 (512) 123-4567',
    startDate: '2020-12-01',
    employmentType: 'full-time'
  },
  {
    id: 'staff-008',
    name: 'Diana Popa',
    email: 'diana.popa@company.com',
    role: 'Product Manager',
    department: 'Product',
    status: 'partially-booked',
    availability: 30,
    billableHours: 100,
    totalHours: 168,
    billableUtilization: 85,
    skills: [
      { name: 'Product Strategy', level: 'expert', yearsOfExperience: 7 },
      { name: 'Agile', level: 'expert', yearsOfExperience: 6 },
      { name: 'User Research', level: 'senior', yearsOfExperience: 5 }
    ],
    languages: ['Romanian', 'English', 'German'],
    programmingLanguages: ['SQL'],
    experience: 9,
    internalRate: 110,
    clientRate: 180,
    currentProjects: ['proj-002', 'proj-001'],
    location: 'Craiova, Romania',
    timezone: 'EET',
    phone: '+39 02 1234 5678',
    startDate: '2020-01-15',
    employmentType: 'full-time'
  },
  {
    id: 'staff-009',
    name: 'Cristian Rusu',
    email: 'cristian.rusu@company.com',
    role: 'Frontend Developer',
    department: 'Engineering',
    status: 'on-leave',
    availability: 0,
    billableHours: 0,
    totalHours: 0,
    billableUtilization: 0,
    skills: [
      { name: 'Vue.js', level: 'senior', yearsOfExperience: 3 },
      { name: 'React', level: 'mid', yearsOfExperience: 2 },
      { name: 'CSS', level: 'expert', yearsOfExperience: 5 }
    ],
    languages: ['Romanian', 'English'],
    programmingLanguages: ['JavaScript', 'TypeScript', 'HTML'],
    experience: 4,
    internalRate: 70,
    clientRate: 125,
    currentProjects: [],
    location: 'Ploiești, Romania',
    timezone: 'EET',
    phone: '+1 (206) 123-4567',
    startDate: '2022-05-01',
    employmentType: 'full-time'
  },
  {
    id: 'staff-010',
    name: 'Raluca Gheorghe',
    email: 'raluca.gheorghe@company.com',
    role: 'Cloud Architect',
    department: 'Infrastructure',
    status: 'available',
    availability: 100,
    billableHours: 0,
    totalHours: 168,
    billableUtilization: 0,
    skills: [
      { name: 'AWS', level: 'expert', yearsOfExperience: 6 },
      { name: 'Azure', level: 'senior', yearsOfExperience: 4 },
      { name: 'Terraform', level: 'senior', yearsOfExperience: 3 }
    ],
    languages: ['Romanian', 'German', 'English'],
    programmingLanguages: ['Python', 'Go', 'HCL'],
    experience: 8,
    internalRate: 100,
    clientRate: 170,
    currentProjects: [],
    location: 'Oradea, Romania',
    timezone: 'EET',
    phone: '+48 22 123 4567',
    startDate: '2020-08-01',
    employmentType: 'full-time'
  }
];

export const mockAssignments: Assignment[] = [
  {
    id: 'assign-001',
    projectId: 'proj-001',
    staffId: 'staff-001',
    role: 'Lead Developer',
    allocation: 100,
    startDate: '2024-01-15',
    endDate: '2024-06-30',
    billableHours: 168,
    hourlyRate: 150,
    totalCost: 25200,
    isTeamLead: true
  },
  {
    id: 'assign-002',
    projectId: 'proj-001',
    staffId: 'staff-002',
    role: 'UX Designer',
    allocation: 60,
    startDate: '2024-01-15',
    endDate: '2024-06-30',
    billableHours: 100,
    hourlyRate: 120,
    totalCost: 12000,
    isTeamLead: false
  },
  {
    id: 'assign-003',
    projectId: 'proj-002',
    staffId: 'staff-005',
    role: 'Mobile Developer',
    allocation: 100,
    startDate: '2024-02-01',
    endDate: '2024-08-15',
    billableHours: 168,
    hourlyRate: 145,
    totalCost: 24360,
    isTeamLead: true
  },
  {
    id: 'assign-004',
    projectId: 'proj-002',
    staffId: 'staff-002',
    role: 'UI Designer',
    allocation: 40,
    startDate: '2024-02-01',
    endDate: '2024-08-15',
    billableHours: 20,
    hourlyRate: 120,
    totalCost: 2400,
    isTeamLead: false
  }
];